---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/inject-cabundle: "true"
    service.beta.openshift.io/serving-cert-secret-name: webhook-certs
  labels:
    name: cloud-ingress-operator-webhook
  name: cloud-ingress-operator-webhook
  namespace: openshift-cloud-ingress-operator
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 5000
  selector:
    app: cloud-ingress-operator
  type: ClusterIP
status:
  loadBalancer: {}
