apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-ingress-operator
  namespace: openshift-cloud-ingress-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cloud-ingress-operator
  template:
    metadata:
      labels:
        name: cloud-ingress-operator
        app: cloud-ingress-operator
    spec:
      serviceAccountName: cloud-ingress-operator
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - preference:
              matchExpressions:
              - key: node-role.kubernetes.io/infra
                operator: Exists
            weight: 1
      tolerations:
      - operator: Exists
        key: node-role.kubernetes.io/infra
        effect: NoSchedule
      volumes:
      - name: trusted-ca
        configMap:
          name: trusted-ca
          defaultMode: 420
          items:
            - key: ca-bundle.crt
              path: tls-ca-bundle.pem
      - name: webhook-certs
        secret:
          secretName: webhook-certs
      containers:
        - name: cloud-ingress-operator
          resources:
          requests:cpu: "200m"
          limits:memory: "1G"
          #TODO Update image
          image: quay.io/mwhittin/cloud-ingress-operator:1
          command:
          - cloud-ingress-operator
          imagePullPolicy: Always
          env:
            # "" so that the cache can read objects outside its namespace
            - name: WATCH_NAMESPACE
              value: "openshift-sre-sshd,openshift-cloud-ingress-operator,openshift-ingress,openshift-ingress-operator,openshift-kube-apiserver,openshift-machine-api"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "cloud-ingress-operator"
          volumeMounts:
            - name: trusted-ca
              mountPath: /etc/pki/ca-trust/extracted/pem
              readOnly: true
          livenessProbe:
            httpGet:
              path: /healthz
              scheme: HTTP
              port: 8000
            initialDelaySeconds: 45
            periodSeconds: 75
        - name: cio-admission
          resources:
          requests:cpu: "200m"
          limits:memory: "1G"
          #TODO Update image
          image: quay.io/mwhittin/cloud-ingress-operator:1
          command:
          - cioadmission
          - "--secure-port=5000"
          - "--tls-cert-file=/var/webhook-certs/tls.crt"
          - "--tls-private-key-file=/var/webhook-certs/tls.key"
          imagePullPolicy: Always
          ports:
          - containerPort: 5000
            protocol: TCP
          volumeMounts:
            - name: webhook-certs
              mountPath: /var/webhook-certs
              readOnly: true
